### ISSUE TITLE
Issue mml3 extension not working even though it is loaded correctly

### ISSUE THREAD

**Issue by tebruno99** [mathjax/mathjax-node-cli#11]
I am trying to execute the following:
`./bin/mml2svg "<m:math><m:mstack><m:mn>101</m:mn><m:msrow><m:mo>-</m:mo><m:mn>63</m:mn></m:msrow><m:msline/></m:mstack></m:math>" --extensions "TeX/noErrors,TeX/noUndefined,MathML/mml3"`

I have done a little bit of debugging and I've been able to determine the extension did load by setting messages to print:
```
Loading [MathJax]/jax/input/TeX/config.js
Loading [MathJax]/jax/input/MathML/config.js
Loading [MathJax]/jax/input/AsciiMath/config.js
Loading [MathJax]/jax/output/SVG/config.js
Loading [MathJax]/jax/output/CommonHTML/config.js
Loading [MathJax]/extensions/toMathML.js
Loading [MathJax]/extensions/TeX/noErrors.js
Loading [MathJax]/extensions/TeX/noUndefined.js
Loading [MathJax]/extensions/MathML/mml3.js
Loading [MathJax]/jax/element/mml/jax.js
Loading [MathJax]/jax/input/TeX/jax.js
Loading [MathJax]/jax/output/SVG/jax.js
Loading [MathJax]/extensions/TeX/AMSmath.js
Loading [MathJax]/extensions/TeX/AMSsymbols.js
Loading [MathJax]/extensions/TeX/autoload-all.js
Loading [MathJax]/jax/output/SVG/fonts/TeX/fontdata.js
Loading [MathJax]/jax/input/AsciiMath/jax.js
Loading [MathJax]/jax/input/MathML/jax.js
MathML - Unknown node type: mstack
```

I've tested the exact same MathML using a simple example.html and it rendered to svg using MathJax.js?config=TeX-MML-AM_SVG so I know everything is valid.

**Comment by dpvc** [comment]
The mml3 extension uses XSLT transformations to convert the MathML3 constructs into MathML that MathJax understands, and mathjax-node uses the JSDOM library to implement the DOM needed by MathJax to do its work.  Unfortunately, JSDOM doesn't implement the XSLTProcessor, and so mathjax-node can't do the XSLT transformation.  That is why you are getting the error message you are seeing, because the nodes have been left as they were as tags that mathjax-node doesn't understand.

I did a quick check to see if there was an XSLTProcessor extension to JSDOM, but I don't see one.  So for now, there doesn't seem to be a way to get this to work in mathjax-node.  The long-term solution is to convert the mml3 extension to use javascript rather than XSLT to do the conversion (like the content-mathml extension), but that is not currently high on our priority list.

**Comment by ruirui19** [comment]
Hi there, is there any updates on this issue?

**Comment by dpvc** [comment]
@ruirui19, it is unlikely that there will be work done on this, as mathjax-node is based on MathJax v2, and that is no longer under development now that version 3 is out.  Since MathJax v3 can be used in node directly, without the hacks used in mathjax-node, you might find that that meets your server-side needs.  The mml3 extension was recently added to version 3 (see mathjax/MathJax#2515), so you should be able to make use of the elementary math tags in version 3 within node, just as you can with version 2 in a browser.
